### ISSUE TITLE
NoSuchMethodError when building

### ISSUE THREAD

**Issue by joprice** [tptodorov/sbt-cloudformation#11]
When I try to build, I get a binary compat error. Is `sbt-cross-building` even needed if you're only targeting a single version (`CrossBuilding.crossSbtVersions := Seq("0.13")`)?

```
[error] (*:allDependencies) java.lang.NoSuchMethodError: sbt.ScalaArtifacts$.toolDependencies(Ljava/lang/String;Ljava/lang/String;)Lscala/collection/Seq;
[error] Total time: 0 s, completed Jul 3, 2016 2:09:58 PM
> last *:allDependencies
java.lang.NoSuchMethodError: sbt.ScalaArtifacts$.toolDependencies(Ljava/lang/String;Ljava/lang/String;)Lscala/collection/Seq;
    at sbt.SbtCrossCompat$$anonfun$allDependenciesSetting$1.apply(SbtCrossCompat.scala:14)
    at sbt.SbtCrossCompat$$anonfun$allDependenciesSetting$1.apply(SbtCrossCompat.scala:8)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by joprice** [comment]
Just noticed that the unattended pr #10 removes these settings, along with the autoplugin upgrade.

**Comment by tptodorov** [comment]
try 0.6.0. Just released it.

**Comment by joprice** [comment]
Works great. Thanks!
